version: '3.8'

services:
  # Como vamos usar Supabase (cloud), não precisamos do PostgreSQL local
  # Mas mantenho aqui caso queira ambiente local de desenvolvimento
  
  # postgres:
  #   image: postgres:15-alpine
  #   container_name: nestjs-postgres
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: nestjs_db
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev

volumes:
  postgres_data: